Swapnil Supe

24102C2002

R Programming Week 11

#PART 1 — DATA FRAMES

Load MASS package and display painters

In [ ]:
library(MASS)

painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

Summary of School

In [ ]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

Attach the data frame

In [ ]:
attach(painters)

summary(School)
summary(Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

In [ ]:
library(MASS)

painters <- MASS::painters

attach(painters)

summary(School)
summary(Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

Detach the data frame

In [ ]:
detach(painters)

summary(School)

ERROR: Error: object 'School' not found

Subset where School = F

In [ ]:
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

Same subset using indexing

In [ ]:
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

Subset where Composition <= 6

In [ ]:
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

Remove columns 3 and 5

In [ ]:
subset(painters, School == "F", select = c(-3, -5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

Split data according to School

In [ ]:
splitted = split(painters, painters$School)

splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

Display individual split

In [ ]:
splitted$A
splitted$B
splitted$C
splitted$D
splitted$E
splitted$F
splitted$G
splitted$H

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A

             Composition Drawing Colour Expression School
F. Zucarro   10          13       8      8         B
Fr. Salviata 13          15       8      8         B
Parmigiano   10          15       6      6         B
Primaticcio  15          14       7     10         B
T. Zucarro   13          14      10      9         B
Volterra     12          15       5      8         B

            Composition Drawing Colour Expression School
Barocci     14          15       6     10         C
Cortona     16          14      12      6         C
Josepin     10          10       6      2         C
L. Jordaens 13          12       9      6         C
Testa       11          15       0      6         C
Vanius      15          15      12     13         C

              Composition Drawing Colour Expression School
Bassano        6           8      17     0          D
Bellini        4           6      14     0          D
Giorgione      8           9      18     4          D
Murillo        6           8      15     4          D
Palma Giovane 12           9      14     6          D
Palma Vecchio  5           6      16     0          D
Pordenone      8          14      17     5          D
Tintoretto    15          14      16     4          D
Titian        12          15      18     6          D
Veronese      15          10      16     3          D

            Composition Drawing Colour Expression School
Albani      14          14      10      6         E
Caravaggio   6           6      16      0         E
Corregio    13          13      15     12         E
Domenichino 15          17       9     17         E
Guercino    18          10      10      4         E
Lanfranco   14          13      10      5         E
The Carraci 15          17      13     13         E

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

            Composition Drawing Colour Expression School
Diepenbeck  11          10      14      6         G
J. Jordaens 10           8      16      6         G
Otho Venius 13          14      10     10         G
Rembrandt   15           6      17     12         G
Rubens      18          13      17     17         G
Teniers     15          12      13      6         G
Van Dyck    15          10      17     13         G

        Composition Drawing Colour Expression School
Bourdon 10           8      8       4         H
Le Brun 16          16      8      16         H
Le Suer 15          15      4      15         H
Poussin 15          17      6      15         H

Check whether a split object is a data frame

In [ ]:
is.data.frame(splitted$A)

[1] TRUE

#PART 2 — IMPORTING EXCEL DATA

Create sample Excel file

Install and load readxl

In [ ]:
import pandas as pd

sheet1 = pd.DataFrame({
    "Variable 1": [1, 2, 3, 4, 5],
    "Variable 2": [10, 20, 30, 40, 50],
    "Variable 3": [100, 200, 300, 400, 500]
})

sheet2 = pd.DataFrame({
    "Variable 4": [6, 7, 8, 9, 10],
    "Variable 5": [110, 120, 130, 140, 150],
    "Variable 6": [110, 210, 310, 410, 510]
})

with pd.ExcelWriter("spexcel.xlsx") as writer:
    sheet1.to_excel(writer, sheet_name="Sheet1", index=False)
    sheet2.to_excel(writer, sheet_name="Sheet2", index=False)

print("spexcel.xlsx created successfully")

In [ ]:
install.packages("readxl", repos = "https://cloud.r-project.org")

library(readxl)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Read first Excel sheet

In [ ]:
dataspexcel = read_excel("spexcel.xlsx", sheet = 1)

dataspexcel

ERROR: Error: `path` does not exist: ‘spexcel.xlsx’

Extract variables

In [ ]:
dataspexcel$`Variable 1`

dataspexcel$`Variable 2`

mean(dataspexcel$`Variable 1`)

Read second Excel sheet

In [ ]:
dataspexcel2 = read_excel("spexcel.xlsx", sheet = 2)

dataspexcel2

Extract second-sheet variables

In [ ]:
dataspexcel2$`Variable 4`

dataspexcel2$`Variable 5`

dataspexcel2$`Variable 6`

mean(dataspexcel2$`Variable 6`)

Read maximum 3 rows

In [ ]:
dataspexcel4 = read_excel("spexcel.xlsx", n_max = 3)

dataspexcel4

Read Excel range

In [ ]:
read_excel("spexcel.xlsx", range = "C1:E7")

Read using R1C1 notation

In [ ]:
read_excel("spexcel.xlsx", range = "R1C2:R2C5")

#PART 3 — SPSS DATA

In [ ]:
install.packages("foreign", repos = "https://cloud.r-project.org")

library(foreign)

# data = read.spss("datafile.sav")

#PART 4 — HTML DATA

In [ ]:
install.packages("XML", repos = "https://cloud.r-project.org")

library(XML)

# data = readHTMLTable("filename")

#PART 5 — OTHER DATA FILES

In [ ]:
# Octave / MATLAB
# read.octave("path/to/file")

# SYSTAT
# read.systat("path/to/file")

# SAS XPORT
# read.xport("path/to/file")

# Stata
# read.dta("path/to/file")

#PART 6 — SAVING AND WRITING DATA

Create vector

In [ ]:
x = c(1:100)

x

Write data to file

In [ ]:
write(x, file = "shalabh")

Write with columns and separator

In [ ]:
write(
  x,
  file = "data.txt",
  ncolumns = 5,
  append = FALSE,
  sep = " "
)

#PART 7 — CSV DATA

Write CSV

In [ ]:
write.csv(x, file = "output.csv")

Write table

In [ ]:
write.table(x, file = "output.txt")

#PART 8 — ABSOLUTE AND RELATIVE FREQUENCIES

Create gender data

In [ ]:
gender <- c(1, 2, 1, 2, 1, 1, 1, 2, 1, 1)

gender

Absolute frequency

In [ ]:
table(gender)

Relative frequency

In [ ]:
table(gender) / length(gender)

#PART 9 — PIZZA HOME DELIVERY DATA

Enter direction data

In [ ]:
direction = c(
1,1,2,1,2,3,2,2,3,3,3,1,2,3,2,2,3,1,1,3,3,1,2,
1,3,3,3,2,2,2,2,1,2,2,1,1,1,3,2,2,1,2,3,2,2,1,
2,3,3,2,1,2,2,3,1,1,2,1,2,3,2,3,2,2,3,1,2,3,3,3,
2,1,1,1,2,1,1,2,1,2,3,3,1,2,3,3,2,1,2,3,2,1,3,
2,2,2,2,3,2,2
)

direction

Check number of observations

In [ ]:
length(direction)

Absolute frequency

In [ ]:
table(direction)

Relative frequency

In [ ]:
table(direction) / length(direction)

#PART 10 — PARTITION VALUES / QUANTILES

Enter marks

In [ ]:
marks = c(
68, 82, 63, 86, 34,
96, 41, 89, 29, 51,
75, 77, 56, 59, 42
)

marks

Default quantiles

In [ ]:
quantile(marks)

Specify probabilities

In [ ]:
quantile(
  marks,
  probs = c(0, 0.25, 0.5, 0.75, 1)
)

Custom probabilities

In [ ]:
quantile(
  marks,
  probs = c(0, 0.20, 0.4, 0.6, 0.8, 1)
)

#PART 11 — SCATTER PLOT

Enter height data

In [ ]:
height = c(
166,125,130,142,147,159,159,147,165,156,
149,164,137,166,135,142,133,136,127,143,
165,121,142,148,158,146,154,157,124,125,
158,159,164,143,154,152,141,164,131,152,
152,161,143,143,139,131,125,145,140,163
)

height

Scatter plot

In [ ]:
plot(height)

Scatter plot with red points

In [ ]:
plot(height, col = "red")

#PART 12 — BAR PLOTS

Basic gender barplot

In [ ]:
gender = c(1, 2, 1, 2, 1, 1, 1, 2, 1, 1)

barplot(gender)

Absolute frequency barplot

In [ ]:
table(gender)

barplot(table(gender))

Relative frequency barplot

In [ ]:
table(gender) / length(gender)

barplot(table(gender) / length(gender))

#PART 13 — DIRECTION BAR PLOTS

Direct direction barplot

In [ ]:
barplot(direction)

Frequency barplot

In [ ]:
barplot(table(direction))

Relative-frequency barplot

In [ ]:
barplot(table(direction) / length(direction))

Add colours

In [ ]:
barplot(
  table(direction),
  col = c("red", "green", "blue")
)

Add title

In [ ]:
barplot(
  table(direction),
  col = c("red", "green", "blue"),
  main = "Directions of food delivery"
)

Add legend

In [ ]:
barplot(
  table(direction),
  col = c("red", "green", "blue"),
  main = "Directions of food delivery",
  legend.text = c("dir1", "dir2", "dir3")
)

Add subtitle

In [ ]:
barplot(
  table(direction),
  col = c("red", "green", "blue"),
  main = "Directions of food delivery",
  legend.text = c("dir1", "dir2", "dir3"),
  sub = "Three directions"
)

FINAL BARPLOT

In [ ]:
barplot(
  table(direction),
  col = c("red", "green", "blue"),
  main = "Directions of food delivery",
  legend.text = c("dir1", "dir2", "dir3"),
  sub = "Three directions",
  xlab = "Food Delivery Directions",
  ylab = "Number of Deliveries"
)

In [ ]:
cat("
EXPERIMENT SUMMARY
------------------

1. Data Frames:
   - Loaded and examined the painters data set.
   - Used summary(), attach(), detach(), subset() and split().
   - Performed row and column selection.

2. Data Handling:
   - Read Excel data using read_excel().
   - Extracted variables from Excel data.
   - Read selected rows and ranges.
   - Used write(), write.csv() and write.table().

3. Statistical Functions:
   - Calculated absolute frequencies using table().
   - Calculated relative frequencies.
   - Calculated partition values using quantile().

4. Graphics:
   - Created scatter plots using plot().
   - Created absolute and relative frequency bar plots.
   - Added colours, title, legend, subtitle, x-axis label and y-axis label.

All commands from the given R lecture practical were performed in Google Colab.
")