# NPTEL R Programming – Week 7
## More Sequences, Dates, Alphabets, Repeats, Sorting, Ordering, Mode and Lists

This notebook contains Google Colab-ready **R code cells** based on the uploaded NPTEL Week 7 notes (Lectures 26–30).

### Topics
- Numeric sequences
- Date sequences
- Alphabet sequences
- `rep()` and repetitions
- Sorting with `sort()`
- Ordering with `order()`
- Object mode with `mode()`
- Lists
- Accessing list elements

## 1. Basic Numeric Sequences

In [1]:
# Continuous sequences with unit increment/decrement

1:10
10:1
5:15
15:5

-1:-10
-10:-1
-5:-15
-15:-5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [2]:
# Numeric sequences with decimal starting values

1.23:10
1.23:10.54
10.54:2.23

-1.23:-10
-5.23:6

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

## 2. Sequences Using `seq()`

In [3]:
# Basic seq() examples

seq(10)
seq(1:10)

# Sequence with a predefined variable

x <- 2
seq(1, x, x / 10)

x <- 50
seq(0, x, x / 10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 1.0 1.2 1.4 1.6 1.8 2.0

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [4]:
# Store the outcome of a sequence

x <- seq(1, 50, 1 / 2)
x

y <- 2 * x
y

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

## 3. Sequence as an Index Vector

In [5]:
x <- c(9, 8, 7, 6)

ind <- seq(along = x)

ind

# Access a value through the index vector
x[ind[2]]

[1] 1 2 3 4

[1] 8

## 4. Current Date and Time

In [6]:
# Current time and date from the computer system

Sys.time()

# Current date from the computer system

Sys.Date()

[1] "2026-09-14 14:09:18 UTC"

[1] "2026-09-14"

## 5. Sequences of Dates

In [7]:
# Sequence of the first day of years

seq(
  as.Date("2010-01-01"),
  as.Date("2017-01-01"),
  by = "years"
)

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [8]:
# Sequence of days

seq(
  as.Date("2017-01-01"),
  by = "days",
  length.out = 6
)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [9]:
# Sequence of months

seq(
  as.Date("2017-01-01"),
  by = "months",
  length.out = 6
)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [10]:
# Sequence by years

seq(
  as.Date("2017-01-01"),
  by = "years",
  length.out = 6
)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [11]:
# Sequence with start and end dates, going backwards by month

startdate <- as.Date("2016-01-01")
enddate <- as.Date("2017-01-01")

out <- seq(
  enddate,
  startdate,
  by = "-1 month"
)

out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

## 6. Lowercase Alphabet Sequences

In [12]:
# Lowercase alphabets

letters

# Select alphabets by index

letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

## 7. Uppercase Alphabet Sequences

In [13]:
# Uppercase alphabets

LETTERS

# Select alphabets by index

LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

## 8. Repeats Using `rep()`

In [14]:
# Repeat a value a specific number of times

rep(3.5, times = 10)

rep(1:4, times = 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

In [15]:
# Repeat a complete vector

x <- 1:4
x

rep(x, times = 3)

# Repeat each element

rep(x, each = 3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [16]:
# Using both each and times

rep(1:4, each = 2)

rep(1:4, each = 2, times = 3)

rep(1:4, times = 3, each = 2)

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [17]:
# Repeat each object a different number of times

rep(1:4, 2:5)

ans <- seq(from = 2, to = 8, by = 2)

ans

rep(1:4, ans)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

## 9. Repeating Matrices and Characters

In [18]:
# Repeat a matrix

x <- matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x

rep(x, 3)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [19]:
# Repeat character vectors

rep(c("a", "b", "c"), 2)

rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [20]:
# Repeat for a predefined output length

rep(2, length.out = 5)
rep(2, length = 5)

rep(c(2, 3), length = 5)
rep(c(2, 3, 4), length = 5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

In [21]:
# Character repetition for a predefined length

rep("apple", length = 5)

rep(c("a", "b", "c"), length = 2)

rep(c("a", "b", "c"), length = 5)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

## 10. Sorting with `sort()`

In [22]:
y <- c(8, 5, 7, 6)

y

# Ascending order
sort(y)

# Descending order
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

## 11. Ordering with `order()`

In [23]:
y <- c(9, 8, 5, 7, 6)

y

# Positions that arrange y in ascending order
order(y)

# Positions that arrange y in descending order
order(y, decreasing = TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

## 12. Mode of R Objects

In [24]:
# Mode tells us how an object is stored

mode(2.432)

mode(c(3, 4, 5, 6, 7, 8))

mode("India")

mode(c("India", "CANADA"))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

In [25]:
# Mode of different object types

mode(factor(c("UP", "MP")))

mode(list("India", "USA"))

mode(data.frame(
  x = 1:2,
  y = c("India", "USA")
))

mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

## 13. Lists

In [26]:
# A list can contain objects of different types

x1 <- matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x2 <- matrix(
  nrow = 2,
  ncol = 2,
  data = 5:8,
  byrow = TRUE
)

x1
x2

x1 + x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [27]:
# Changing a matrix element to character data

x1[2, 1] <- "hello"

x1

# This produces an error because x1 is no longer numeric:
# x1 + x2

# Uncomment the next line to see the error:
# x1 + x2

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [28]:
# Lists can contain matrices

x1 <- matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x2 <- matrix(
  nrow = 2,
  ncol = 2,
  data = 5:8,
  byrow = TRUE
)

matlist <- list(x1, x2)

matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [29]:
# Access list elements by position

matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## 14. List Containing Different Object Types

In [30]:
z1 <- list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(
    data = 5:8,
    nrow = 2,
    ncol = 2,
    byrow = TRUE
  )
)

z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## 15. Accessing List Elements with `[[ ]]`

In [31]:
# Access the first element of the list

z1[[1]]

# Extract "juice" from the first element

z1[[1]][2]

[1] "water"    "juice"    "lemonade"

[1] "juice"

In [32]:
# Difference between [ ] and [[ ]]

# [ ] returns a sublist
z1[1]

# [[ ]] extracts the actual list element
z1[[1]]

# Extract the second value from the first list element
z1[[1]][2]

[[1]]
[1] "water"    "juice"    "lemonade"

[1] "water"    "juice"    "lemonade"

[1] "juice"

## Quick Practice

Try changing the examples and execute them again.

1. Create a sequence from 1 to 100 with `seq()`.
2. Generate dates for 12 consecutive months.
3. Select different ranges from `letters` and `LETTERS`.
4. Repeat a vector using both `times` and `each`.
5. Sort your own numeric vector in ascending and descending order.
6. Use `order()` to obtain the positions of sorted values.
7. Create a list containing a character vector, numeric vector and matrix.
8. Extract a specific element from the list using `[[ ]]`.