MISSING DATA

In [ ]:
X = NA

In [ ]:
is.na(X)

[1] TRUE

In [ ]:
X = c(11, NA, 13, NA)
is.na(X)

[1] FALSE  TRUE FALSE  TRUE

How to work with missing data

In [ ]:
x = c(11, NA, 13, NA)
mean(x)

[1] NA

In [ ]:
mean(x, na.rm = TRUE)

[1] 12

MISSING DATA:lOCATION OF MISSING VALUES

In [ ]:
X = c(11,NA,13,NA)
X

[1] 11 NA 13 NA

In [ ]:
which(is.na(X))

[1] 2 4

Missing data

In [ ]:
x= c(11,NA,13,NA)
X

[1] 11 NA 13 NA

In [ ]:
sum(is.na(x))

[1] 2

missing data: finding complete cases

In [ ]:
x= c(11,NA,13,NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

missing data: finding complete data set

In [ ]:
x= c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [ ]:
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

missing data : Handling values

In [ ]:
x= c(11,NA,13,NA)
y = na.omit(x)
y
mean(x)
mean(y)

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

conditional exectuation : if()

In [ ]:
x = 5
x

[1] 5

In [ ]:
if(x > 4) {x * 3}

[1] 15

In [ ]:
x = 3
if (x > 4) {x * 3}

In [ ]:
x = 6
if(x > 3){
  print("The value is more than 3")
}

[1] "Thw value is more than 3"

In [ ]:
x = 2
if(x > 3){
  print("The value is more than 3")
}

conditional exectuation : if  else()

In [ ]:
x = 5
if (x==3) {x = x-1} else{x = 2*x}
x

[1] 10

In [ ]:
x = 3
if (x==3) {x = x-1} else{x = 2*x}
x

[1] 2

In [ ]:
x =6
if(x > 3){
  print("The values is more than 3")
}else {
  print("The value is less than 3")
}

[1] "The values is more than 3"

In [ ]:
x = 2
if(x > 3){
  print("The values is more than 3")
}else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

conditional exectuation : Nested if else if()

In [ ]:
x = 5
if(x == 3){
  x = x-1
}else if(x <3) {
  x = x+5
}else {x = 2*x}
x

[1] 10

In [ ]:
x = 2
if(x == 3){
  x = x-1
}else if(x <3) {
  x = x+5
}else {x = 2*x}
x

[1] 7

In [ ]:
x = 3
if(x == 3){
  x = x-1
}else if(x <3) {
  x = x+5
}else {x = 2*x}
x

[1] 2

conditional execution : ifelse()

In [ ]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
ifelse( x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x = c(7,9,8,4)
ifelse(x %% 2 ==0,"even number","odd number")

[1] "odd number"  "odd number"  "even number" "even number"

execution:switch()

In [ ]:
switch(2,"apple","banana","orange")

[1] "banana"

In [ ]:
switch(1,"apple","banana","orange")

[1] "apple"

In [ ]:
switch("colour","colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [ ]:
switch("volume","colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

In [ ]:
switch(4,"apple","banana","orange")

In [ ]:
switch("size","colour" = "blue", "gender" = "male", "volume" = 50)

In [ ]:
x = c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

In [ ]:
which(x == 14 )

[1] 4

In [ ]:
which(x != 12 )

[1] 1 2 3 4 5

In [ ]:
which(x > 10)

[1] 2 4 6

In [ ]:
x = matrix(nrow=3, ncol=3, data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which(x %% 2 == 1)

[1] 1 3 5 7 9

In [ ]:
which(x %% 2 == 1, arr.ind =TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3